// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNJsQYTXWkilt1-HB8zksG__V_aIwttD4',
    appId: '1:315429577938:web:7480cecfe44d691ab5f90b',
    messagingSenderId: '315429577938',
    projectId: 'alfurqan-4e1c4',
    authDomain: 'alfurqan-4e1c4.firebaseapp.com',
    storageBucket: 'alfurqan-4e1c4.firebasestorage.app',
    measurementId: 'G-M03NS62H5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3n0Hzfn2N1a_U7QE4FYhP67FpxMvefvQ',
    appId: '1:315429577938:android:72c4f360ef05b31eb5f90b',
    messagingSenderId: '315429577938',
    projectId: 'alfurqan-4e1c4',
    storageBucket: 'alfurqan-4e1c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0g24zVxju8uibQhzIT8PaYTIuHiZyF80',
    appId: '1:315429577938:ios:71bb63ff56a14495b5f90b',
    messagingSenderId: '315429577938',
    projectId: 'alfurqan-4e1c4',
    storageBucket: 'alfurqan-4e1c4.firebasestorage.app',
    iosBundleId: 'com.example.alfurqan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0g24zVxju8uibQhzIT8PaYTIuHiZyF80',
    appId: '1:315429577938:ios:71bb63ff56a14495b5f90b',
    messagingSenderId: '315429577938',
    projectId: 'alfurqan-4e1c4',
    storageBucket: 'alfurqan-4e1c4.firebasestorage.app',
    iosBundleId: 'com.example.alfurqan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNJsQYTXWkilt1-HB8zksG__V_aIwttD4',
    appId: '1:315429577938:web:1cbba8c187149e7cb5f90b',
    messagingSenderId: '315429577938',
    projectId: 'alfurqan-4e1c4',
    authDomain: 'alfurqan-4e1c4.firebaseapp.com',
    storageBucket: 'alfurqan-4e1c4.firebasestorage.app',
    measurementId: 'G-JGJNXSY5XQ',
  );
}
